version: 0.2

env:
  git-credential-helper: yes

phases:
  build:
    commands:
      - git config --global user.email "pacofvf@gmail.com"
      - git config --global user.name "Paco Valdez"
      - scripts/codebuild-git-wrapper.sh "$REPO_URL" "$REPO_BRANCH" # These environment variables come from the CFN stack
      - git log | head -100
      - git remote -v
      - git remote add github "$REPO_MIRROR_URL"
      - git remote -v
      - python --version
      - python download_files.py
      - git add data/*
      - git commit -am "Update run for date $(date)"
      - git push origin master
      - git push --force github master
