sites:
    adip:
        name: ADIP
        url: https://datos.cdmx.gob.mx/explore/dataset/{dataset}/download/?format={format}&timezone={timezone}&lang={lang}&use_labels_for_header=true&csv_separator=%2C
        params:
            format: csv
            timezone: America/Mexico_City
            lang: es
        datasets:
            - "fotocivicas"
            - "diagnostico-sobre-la-ciudad-en-el-mundo"
