AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  RepositoryName:
    Description: 'CodeCommit repository name'
    Type: String
  RepositoryCloneUrl:
    Description: 'CodeCommit repository clone URL'
    Type: String
  RepositoryBranch:
    Description: 'CodeCommit repository branch (defaults to master)'
    Type: String
    Default: master
  RepositoryMirrorUrl:
    Description: 'Github repository clone URL'
    Type: String

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'codebuild.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'codecommit:GetBranch'
                  - 'codecommit:GetCommit'
                  - 'codecommit:GetUploadArchiveStatus'
                  - 'codecommit:UploadArchive'
                  - 'codecommit:GitPull'
                  - 'codecommit:GitPush'
                Resource:
                  - !Sub arn:aws:codecommit:*:*:${RepositoryName}
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - '*'
  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'codebuild.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'codebuild:StartBuild'
                  - 'codebuild:ListProjects'
                  - 'codebuild:UpdateProject'
                  - 'iam:PassRole'
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - '*'
  CodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AWS::StackName}-${RepositoryBranch}-CodeBuild'
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: 'aws/codebuild/nodejs:8.11.0'
        EnvironmentVariables:
          - Name: REPO_URL
            Value: !Ref RepositoryCloneUrl
          - Name: REPO_BRANCH
            Value: !Ref RepositoryBranch
          - Name: REPO_MIRROR_URL
            Value: !Ref RepositoryMirrorUrl
      Source:
        Type: CODECOMMIT
        Location: !Ref RepositoryCloneUrl
        BuildSpec: 'buildspec.yml'
      SourceVersion: 'master'
      Artifacts:
        Type: NO_ARTIFACTS
      Description: !Join
        - ''
        - - 'CodeBuild Project for '
          - !Ref 'AWS::StackName'
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Launch CodeBuild Event"
      ScheduleExpression: "cron(0 7 * * ? *)"
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt CodeBuild.Arn
          Id: !Sub '${AWS::StackName}-${RepositoryBranch}-CodeBuild'
          RoleArn: !GetAtt CloudWatchRole.Arn

